version: "3"
services:
  auth_db:
    image: "mongo:latest"
    ports:
      - "9101:27017"
  guild_db:
    image: "mongo:latest"
    ports:
      - "9102:27017"
  auth:
    build: "./services/auth"
    environment:
      - DB_PORT=9101
      - GATEWAY_PORT=9000
    depends_on:
      - "auth_db"
    ports:
      - "9001:9001"
  guild:
    build: "./services/guild"
    environment:
      - DB_PORT=9102
      - GATEWAY_PORT=9000
    depends_on:
      - "guild_db"
    ports:
      - "9002:9002"
  gateway:
    build: "./services/gateway"
    ports:
      - "9000:9000"
    environment:
      - SERVER_PORT=9000
      - AUTH_PORT=9001
      - GUILD_PORT=9002
